"""Add 'currency' field to 'employee' table.

Revision ID: 1fd825cb0401
Revises: f666ce77de75
Create Date: 2025-03-11 09:42:15.638639

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1fd825cb0401"
down_revision: Union[str, None] = "f666ce77de75"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "employee",
        sa.Column(
            "currency",
            sqlmodel.sql.sqltypes.AutoString(),
            server_default="USD",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employee", "currency")
    # ### end Alembic commands ###
