"""Hash passwords.

Revision ID: 29e650e071c8
Revises: 1fd825cb0401
Create Date: 2025-05-06 16:32:57.083946

"""

from typing import Sequence, Union

from alembic import op
from sqlmodel import Session, select

from dundie.models import User
from dundie.utils.user import generate_password_hash, verify_password

# revision identifiers, used by Alembic.
revision: str = "29e650e071c8"
down_revision: Union[str, None] = "1fd825cb0401"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    session = Session(bind=conn)
    users = session.exec(
        select(User).where(~User.password.like("$argon%"))  # type: ignore
    ).all()
    for user in users:
        plain_password = user.password
        hashed_password = generate_password_hash(plain_password)
        if verify_password(plain_password, hashed_password):
            user.password = hashed_password
            session.add(user)
    session.commit()
    # ### end Alembic commands ###
    # ### commands auto generated by Alembic - please adjust! ###


def downgrade() -> None:
    """Downgrade schema."""
    pass
