"""Initial database migration revision.

Revision ID: f666ce77de75
Revises:
Create Date: 2025-03-11 09:14:11.084375

"""

from typing import Sequence, Union

import sqlalchemy as sa  # noqa F401
import sqlmodel  # noqa F401
from alembic import op  # noqa F401

# revision identifiers, used by Alembic.
revision: str = "f666ce77de75"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
