name: CI

# Increase terminal width to avoid pytest errors caused by truncated output.
# Refer to `man bash` for more information on the COLUMNS environment variable.
env:
  COLUMNS: 255

permissions:
  checks: write
  pull-requests: write

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  lint:
    strategy:
      fail-fast: true
      matrix:
        python-version: ['3.13']
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Install the project
        run: uv sync --all-extras --dev
      - name: Look for style errors
        run: uv ruff check --diff dundie tests integration
      - name: Check for importing style
        run: uvx ruff format --check --diff dundie tests integration
  tests:
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.13']
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}
      - name: Run tests
        run: |
          uv run --extra test pytest -v --forked --junitxml=junit.xml -o junit_family=legacy --cov=dundie --cov-branch --cov-report=xml
          uv run --extra test coverage xml
      - name: Publish Test Results in JUnit XML format
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: junit.xml
          check_name: Test Results (Python ${{matrix.python-version}})
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload coverage reports to Codecov
        if: ${{ matrix.python-version == '3.13' }}
        uses: codecov/codecov-action@v5
        continue-on-error: true
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
